### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by lianwenliang** [zhetengbiji/image-tools#2]
var extName = base64.match(/data\:\S+\/(\S+);/)
        if (extName) {
            extName = extName[1]
        } else {
            reject(new Error('base64 error'))
        }
        var fileName = Date.now() + '.' + extName
这里是否可以考虑直接用户固定扩展名，否则效率太低了 
我直接这么用了 var fileName = Date.now()+'.jpg' 这样效率太高很多倍

**Comment by zhetengbiji** [comment]
是否有具体的数据？
