### ISSUE TITLE
base64字符串提取图片格式卡住

### ISSUE THREAD

**Issue by qzsiniong** [zhetengbiji/image-tools#5]
不知道为什么，我的程序一直卡住。
搞了半天才发现是`var extName = base64.match(/data\:\S+\/(\S+);/)`这里执行很慢

于是我改成`var extName = base64.substr(0, 100).match(/data\:\S+\/(\S+);/)`就好了

**Comment by zhetengbiji** [comment]
是单独某个设备才有这个问题吗？其他设备是否正常
如果是的话提供一下设备信息

**Comment by qzsiniong** [comment]
> 是单独某个设备才有这个问题吗？其他设备是否正常
> 如果是的话提供一下设备信息

iphone12 ios14.6
iphone6s ios14.0.1

两个手机都有问题，其他的没试。

base64字符串有805kB。
只要是对该字符串进行match/replace操作都会卡住，substr/indexOf就没问题。

我改了以下两行代码后就正常了

var extName = base64.match(/data\:\S+\/(\S+);/)
↓
var extName = base64.substr(0, 100).match(/data\:\S+\/(\S+);/)

writer.writeAsBinary(base64.replace(/^data:\S+\/\S+;base64,/, ''))
↓
writer.writeAsBinary(base64.substring(base64.indexOf('base64,')+7))

**Comment by zhetengbiji** [comment]
好的，谢谢，已更新

**Comment by zhetengbiji** [comment]
好的，谢谢，已更新
